config/routes.rb
Rails.application.routes.draw do
  resources :event_attendings
  resources :events
  resources :users
  
  root'events#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  
   belongs_to :creator, class_name: "User"
    has_many :event_attendings, foreign_key: :attended_event_id
    has_many :attending_users, through: :event_attendings, source: :attending_user
end

app/models/event_attending.rb
class EventAttending < ApplicationRecord
   belongs_to :attending_user, class_name: "User"
    belongs_to :attended_event, class_name: "Event"
end

app/models/user.rb
class User < ApplicationRecord
  
   has_many :created_events, foreign_key: "creator_id", class_name: "Event"
   has_many :event_attendings, foreign_key: :attending_user_id
  has_many :attended_events, through: :event_attendings, source: :attended_event
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/event_attendings_controller.rb
class EventAttendingsController < ApplicationController
  before_action :set_event_attending, only: %i[ show edit update destroy ]

  # GET /event_attendings or /event_attendings.json
  def index
    @event_attendings = EventAttending.all
  end

  # GET /event_attendings/1 or /event_attendings/1.json
  def show
  end

  # GET /event_attendings/new
  def new
    @event_attending = EventAttending.new
  end

  # GET /event_attendings/1/edit
  def edit
  end

  # POST /event_attendings or /event_attendings.json
  def create
    @event_attending = EventAttending.new(event_attending_params)

    respond_to do |format|
      if @event_attending.save
        format.html { redirect_to event_attending_url(@event_attending), notice: "Event attending was successfully created." }
        format.json { render :show, status: :created, location: @event_attending }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @event_attending.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /event_attendings/1 or /event_attendings/1.json
  def update
    respond_to do |format|
      if @event_attending.update(event_attending_params)
        format.html { redirect_to event_attending_url(@event_attending), notice: "Event attending was successfully updated." }
        format.json { render :show, status: :ok, location: @event_attending }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @event_attending.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /event_attendings/1 or /event_attendings/1.json
  def destroy
    @event_attending.destroy

    respond_to do |format|
      format.html { redirect_to event_attendings_url, notice: "Event attending was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event_attending
      @event_attending = EventAttending.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def event_attending_params
      params.require(:event_attending).permit(:attended_event_id, :attending_user_id)
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: %i[ show edit update destroy ]

  # GET /events or /events.json
  def index
    @events = Event.all
  end

  # GET /events/1 or /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events or /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to event_url(@event), notice: "Event was successfully created." }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1 or /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to event_url(@event), notice: "Event was successfully updated." }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1 or /events/1.json
  def destroy
    @event.destroy

    respond_to do |format|
      format.html { redirect_to events_url, notice: "Event was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def event_params
      params.require(:event).permit(:name, :date, :creator_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/event_attendings_helper.rb
module EventAttendingsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/event_attendings/_form.html.erb
<%= form_with(model: event_attending, local: true) do |form| %>
  <% if event_attending.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event_attending.errors.count, "error") %> prohibited this event_attending from being saved:</h2>

      <ul>
        <% event_attending.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :attended_event_id %>
    <%= form.number_field :attended_event_id %>
  </div>

  <div class="field">
    <%= form.label :attending_user_id %>
    <%= form.number_field :attending_user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/event_attendings/edit.html.erb
<h1>Editing Event Attending</h1>

<%= render 'form', event_attending: @event_attending %>

<%= link_to 'Show', @event_attending %> |
<%= link_to 'Back', event_attendings_path %>

app/views/event_attendings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Event Attendings</h1>

<table>
  <thead>
    <tr>
      <th>Attended event</th>
      <th>Attending user</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @event_attendings.each do |event_attending| %>
      <tr>
        <td><%= event_attending.attended_event_id %></td>
        <td><%= event_attending.attending_user_id %></td>
        <td><%= link_to 'Show', event_attending %></td>
        <td><%= link_to 'Edit', edit_event_attending_path(event_attending) %></td>
        <td><%= link_to 'Destroy', event_attending, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Event Attending', new_event_attending_path %>

app/views/event_attendings/new.html.erb
<h1>New Event Attending</h1>

<%= render 'form', event_attending: @event_attending %>

<%= link_to 'Back', event_attendings_path %>

app/views/event_attendings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Attended event:</strong>
  <%= @event_attending.attended_event_id %>
</p>

<p>
  <strong>Attending user:</strong>
  <%= @event_attending.attending_user_id %>
</p>

<%= link_to 'Edit', edit_event_attending_path(@event_attending) %> |
<%= link_to 'Back', event_attendings_path %>

app/views/events/_form.html.erb
<%= form_with(model: event, local: true) do |form| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
        <% event.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :date %>
    <%= form.text_field :date %>
  </div>

  <div class="field">
    <%= form.label :creator_id %>
    <%= form.number_field :creator_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Events</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
   
     <p><strong> Events that will be Occured in the future :</strong></p>
    <% @events.each do |event| %>
    <% if event.date > Date.today %>
      <tr>
        <td><%= event.name %></td>
        <td><%= event.date %></td>
      
        <td><%= link_to 'Show', event %></td>
        <td><%= link_to 'Edit', edit_event_path(event) %></td>
        <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
    <% end %>
    </p>
  </tbody>
</table>

<br>

<%= link_to 'New Event', new_event_path %>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @event.name %>
</p>

<p>
  <strong>Date:</strong>
  <%= @event.date %>
</p>

<p>
  <strong>Creator:</strong>
  <%= @event.creator_id %>
  </p>
  <p>
  <strong> Attending Users :</strong>
     <ol> <% @event.attending_users.each do |user| %>
       <li>
        <%= user.name %> 
        </li>
        <% end %> </ol>
    
</p>

<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NewApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <table>
  <tr>
    <th>Name:</th>
    <th>Events Created by this User:</th>
    <th> Attended Events by this User:</th>
   
  </tr>
  <tr>
    <td> <%= @user.name %> </td>
    <td>   <ol> <% @user.created_events.each do |event| %>
    <li>
        <%= event.name %> 
        </li>
        <% end %> </ol>
    </td>
     <td>   <ol> <% @user.attended_events.each do |event| %>
    <li>
        <%= event.name %> 
        </li>
        <% end %> </ol>
    </td>
   
  </tr>
  </table>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>